# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  # Development
  dev:
    desc: Start the development server
    cmds:
      - uv run fastapi dev main.py

  # Production
  run:
    desc: Start the production server
    cmds:
      - uv run fastapi run main.py

  # Format
  format:
    desc: Format the code using Black
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  # Migrate
  db:migrations:
    desc: Generate a new database migration
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  db:migrate:
    desc: Run database migrations
    cmds:
      - uv run alembic upgrade head

  db:downgrade:
    desc: Downgrade the database to the previous version
    cmds:
      - uv run alembic downgrade -1

  # Docker
  docker:up:
    desc: Start the Docker containers
    cmds:
      - docker-compose up -d
  
  docker:down:
    desc: Stop the Docker containers
    cmds:
      - docker-compose down -v
    
  docker:stop:
    desc: Stop the Docker containers without removing volumes
    cmds:
      - docker-compose stop

  # Stripe
  stripe:login:
    desc: Login to stripe
    cmds:
      - docker-compose run stripe login
  
  stripe:listen:
    desc: Listen to webhook
    cmds:
      - docker-compose run stripe listen --forward-to host.docker.internal:8000/api/v1/stripe/webhook

  stripe:test:
    desc: Trigger payment success event
    cmds:
      - docker-compose run stripe trigger payment_intent.succeeded

  stripe:test-product:
    desc: Trigger product created
    cmds:
      - docker-compose run stripe trigger product.created