"""'added order and order item'

Revision ID: 007b2bd311cf
Revises: bae5fcad1c6b
Create Date: 2026-04-19 13:33:32.765860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "007b2bd311cf"
down_revision: Union[str, Sequence[str], None] = "bae5fcad1c6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_uid"], ["users.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("user_uid"),
    )
    op.create_index(op.f("ix_orders_uid"), "orders", ["uid"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("order_uid", sa.UUID(), nullable=False),
        sa.Column("product_uid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["order_uid"], ["orders.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_uid"], ["products.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_order_items_uid"), "order_items", ["uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_uid"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_orders_uid"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
