"""added total amount 'in' order table

Revision ID: 43d9397973df
Revises: 83d959bc0b6c
Create Date: 2026-05-04 08:36:14.228760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43d9397973df"
down_revision: Union[str, Sequence[str], None] = "83d959bc0b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("total_amount", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "total_amount")
    # ### end Alembic commands ###
