"""'added relationship'

Revision ID: 45f73b8e69a9
Revises: b95ff4e725fc
Create Date: 2026-04-17 12:36:18.361553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f73b8e69a9'
down_revision: Union[str, Sequence[str], None] = 'b95ff4e725fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_uid', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('sub_category_uid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['category_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'sub_categories', ['sub_category_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'sub_category_uid')
    op.drop_column('products', 'category_uid')
    # ### end Alembic commands ###
