"""'added the cart and cart items'

Revision ID: bae5fcad1c6b
Revises: ac0f497b9505
Create Date: 2026-04-19 09:37:38.035769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae5fcad1c6b'
down_revision: Union[str, Sequence[str], None] = 'ac0f497b9505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_uid')
    )
    op.create_index(op.f('ix_carts_uid'), 'carts', ['uid'], unique=False)
    op.create_table('cart_items',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_uid', sa.UUID(), nullable=False),
    sa.Column('product_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_uid'], ['carts.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_cart_items_uid'), 'cart_items', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_uid'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_carts_uid'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
